<?xml version="1.0"?>
<robot xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" name="human_model" >
       
<xacro:include filename="props_global.urdf.xacro" />
  
<xacro:macro name="human_arm" params="side reflect boolside">
    <link name="${side}_arm_mount"/>

    <link name="${side}_shoulder_0"/>

    <link name="${side}_shoulder_1"/>

    <link name="${side}_upper_arm">
      <visual>
        <origin xyz="${upper_arm_length/2} 0 0" rpy="0 ${PI_DIV_2} 0" />
        <geometry>
	        <cylinder radius="0.05" length="${upper_arm_length}" />
        </geometry>
      </visual>
    </link>
      
    <link name="${side}_elbow_0"/>

    <link name="${side}_forearm">
      <visual>
        <origin xyz="${forearm_length/2} 0 0" rpy="0 ${PI_DIV_2} 0" />
        <geometry>
	        <cylinder radius="0.025" length="${forearm_length}" />
        </geometry>
      </visual>
    </link>

    <link name="${side}_wrist_0"/>

    <link name="${side}_hand">
      <visual>
        <origin xyz="${hand_length/2} 0 0" rpy="0 0 0" />
        <geometry>
	        <box size="${hand_length} 0.05 .005" />
        </geometry>
      </visual>
    </link>

    <link name="${side}_hand_tip"/>

    <!-- Joints -->

    <joint name="${side}_arm_mount" type="fixed">
      <origin xyz="0 ${reflect*shoulder_offset_width} ${shoulder_offset_height}" rpy="0 0 ${reflect*PI_DIV_2}" />
      <parent link="torso" />
      <child link="${side}_arm_mount" />
    </joint>

    <!-- SHOULDER : spherical -->

        <joint name="${side}_shoulder_0" type="revolute">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <axis xyz="0 1 0" />
          <parent link="${side}_arm_mount" />
          <child link="${side}_shoulder_0" />
          <limit lower="${-PI_DIV_2}" upper="${PI_DIV_2}" effort="${max_effort}" velocity="${max_velocity}"  />
        </joint>

        <xacro:if value="${boolside}">
          <joint name="left_shoulder_1" type="revolute">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <axis xyz="0 0 1" />
            <parent link="left_shoulder_0" />
            <child link="left_shoulder_1" />
            <limit lower="${-TPI_DIV_4}" upper="${PI_DIV_2}" effort="${max_effort}" velocity="${max_velocity}"  />
          </joint>
        </xacro:if>
        <xacro:unless value="${boolside}">
          <joint name="right_shoulder_1" type="revolute">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <axis xyz="0 0 1" />
            <parent link="right_shoulder_0" />
            <child link="right_shoulder_1" />
            <limit lower="${-PI_DIV_2}" upper="${TPI_DIV_4}" effort="${max_effort}" velocity="${max_velocity}"  />
          </joint>
        </xacro:unless>

        <joint name="${side}_shoulder_2" type="revolute">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <axis xyz="1 0 0" />
          <parent link="${side}_shoulder_1" />
          <child link="${side}_upper_arm" />
          <limit lower="${-PI_DIV_2}" upper="${PI_DIV_2}" effort="${max_effort}" velocity="${max_velocity}"  />
        </joint>
    
    <!-- END SHOULDER -->
    <xacro:if value="${boolside}">
      <joint name="left_elbow_0" type="revolute">
        <origin xyz="${upper_arm_length} 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <parent link="left_upper_arm" />
        <child link="left_elbow_0" />
        <limit lower="${-PI}" upper="0.0" effort="${max_effort}" velocity="${max_velocity}"  />
      </joint>

      <joint name="left_elbow_1" type="revolute">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <parent link="left_elbow_0" />
        <child link="left_forearm" />
        <limit lower="${-PI}" upper="0.0" effort="${max_effort}" velocity="${max_velocity}"  />
      </joint>
    </xacro:if>
    <xacro:unless value="${boolside}">
      <joint name="right_elbow_0" type="revolute">
        <origin xyz="${upper_arm_length} 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <parent link="right_upper_arm" />
        <child link="right_elbow_0" />
        <limit lower="0.0" upper="${PI}" effort="${max_effort}" velocity="${max_velocity}"  />
      </joint>

      <joint name="right_elbow_1" type="revolute">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <parent link="right_elbow_0" />
        <child link="right_forearm" />
        <limit lower="0.0" upper="${PI}" effort="${max_effort}" velocity="${max_velocity}"  />
      </joint>
    </xacro:unless>

    <joint name="${side}_wrist_0" type="revolute">
      <origin xyz="${forearm_length} 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <parent link="${side}_forearm" />
      <child link="${side}_wrist_0" />
      <limit lower="${-PI_DIV_4}" upper="${PI_DIV_4}" effort="${max_effort}" velocity="${max_velocity}"  />
    </joint>

    <joint name="${side}_wrist_1" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <parent link="${side}_wrist_0" />
      <child link="${side}_hand" />
      <limit lower="${-PI_DIV_2}" upper="${PI_DIV_2}" effort="${max_effort}" velocity="${max_velocity}"  />
    </joint>

    <joint name="${side}_hand" type="fixed">
      <origin xyz="${hand_length} 0 0" rpy="0 0 0" />
      <parent link="${side}_hand" />
      <child link="${side}_hand_tip" />
    </joint>
</xacro:macro>
</robot>
